### ISSUE TITLE
Check device unnumbered interface capabilities

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#107]
We should check whether devices used in a lab support unnumbered IPv4 or IPv6 interfaces (if specified in the lab topology needed) after the link transformation phase, and report errors if unnumbered interfaces are used on devices not supporting them.

We need addressing capabilities in **devices** part of system defaults with at least these option:

* Support for unnumbered IPv4 interfaces (**unnumbered_ipv4**)
* Support for IPv6 LLA-only interfaces (**ipv6_lla_only**)
* Support for Cumulus-style v4-over-v6 EBGP sessions over unnumbered external interfaces (**unnumbered_ebgp**)

Anything else @jbemmel @ssasso?

**Comment by jbemmel** [comment]
I'm thinking these could be modeled as 'features' of the 'initial' module, as a more fine grained way of expressing "supported_on"

Similar to bgp addpath for example (although one can opt to model that as a custom one-off module too)

```
devices:
  srlinux:
    modules:
      initial:
        ipv4:
          unnumbered: False
        ipv6:
          lla_only: True
      bgp:
       ipv4:
         ipv6_nexthops: True
      ...
```

**Comment by ipspace** [comment]
@jbemmel: Love this idea. Thank you.

**Comment by ipspace** [comment]
Added **features** attribute to **defaults.devices**. CSR example:

```
devices:
  csr:
    features:
      initial:
        ipv4:
          unnumbered: True
        ipv6:
          lla: True
      ospf:
        unnumbered: True
      isis:
        unnumbered:
          ipv4: True
          ipv6: True
          network: True
```

Notes on IS-IS:
* vSRX can do IPv6, but not IPv4 unnumbered, therefore I split that in address families
* NXOS can do P2P unnumbered links but not multi-access ones -- the **network** flag.

@jbemmel I was guessing at what SR Linux and SR OS can do. Please fix the features settings in `topology-defaults.yml` if needed. Thank you!
