### ISSUE TITLE
s-hook links

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#116]
Some use cases require links that connect 2 ports of the same node. Due to the representation as a dict, these cannot currently be represented (type "p2p" results in an error)

Proposal: new link type ("loopback" or "s-hook")

**Comment by ipspace** [comment]
We could also do it right and bite the bullet. Release 1.1 will change a lot of existing data structures and it might be best to be done with refactoring (we're aware of) before it goes out and I announce the plugins.

How about a new link attribute (**attach**??? any better idea?) that is a list of attached nodes, each node being a dictionary of interface attributes. It would be created automatically during the initial phase of the transformation process or you could specify it in the topology file.

The changes probably wouldn't propagate much beyond **links.py**, **modules/__init.py__** and the **bgp** module. There's rain/show forecasted for tomorrow, so maybe I could squeeze it in ;)

/cc @ssasso

**Comment by jbemmel** [comment]
Perhaps "**nodes**"?

**Comment by ipspace** [comment]
That was my first thought. However, having **links** within **nodes** is already bad enough, adding **nodes** to **links** might just increase the confusion.

Would you find **interfaces** acceptable?

**Comment by ipspace** [comment]
@jbemmel: Initial commit is in the **links** branch. All tests pass (which I find amazing, but who am I to complain).

Still missing:

* LAN interfaces are collected in a dictionary. Multiple interfaces to the same node still won't work on a LAN link. They should work on a P2P link (not tested though)
* Documentation

You could take it for a spin if you wish and tell me how it works ;)

**Comment by jbemmel** [comment]
Tried:
```
- interfaces:
  - node: r1
  - node: r1
  prefix: False
```

Result:
```
- ifindex: 3
  ifname: 1/x1/1/c3
  linkindex: 6
  name: r1 -> r1
  provider_ifname: eth3
  type: p2p
- ifindex: 4
  ifname: 1/x1/1/c4
  linkindex: 6
  name: r1 -> r1
  neighbors:
    r1:
      ifname: 1/x1/1/c3
  provider_ifname: eth4
  remote_id: 1
  remote_ifindex: 3
  type: p2p
```

In Containerlab:
```
- endpoints:
    - "r1:eth3"
    - "r1:eth4"
```

So it looks like it does generate things correctly, but the asymmetry is a bit odd.
