### ISSUE TITLE
Provider-Specific Device Properties

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#138]
For example, on Containerlab we have provider_kind which gets copied to node.kind

Instead, each provider could declare attributes:
```
clab:
 attributes:
  node: [ kind, type ]
 devices: 
  srlinux:
   kind: srl
   type: ixrd2
```

and then those would be copied to node.\<provider\>.xxx:
```
clab:
 kind: srl
 type: ixrd2
```
and referenced in templates as {{ clab.kind }}, etc.

_Originally posted by @jbemmel in https://github.com/ipspace/netsim-tools/discussions/96_

**Comment by ipspace** [comment]
I would start with moving provider-specific device data into **devices** so someone focusing on a particular device can figure out what's going on without inspecting several places in the default settings hierarchy.

For example, Arista EOS entry would look like:

```
eos:
  interface_name: Ethernet%d
  mgmt_if: Management1
  image:
    libvirt: arista/veos
    virtualbox: arista/veos
  group_vars:
    ansible_user: vagrant
    ansible_ssh_pass: vagrant
    ansible_network_os: eos
    ansible_connection: network_cli
  clab:
    provider_interface_name: eth%d
    mgmt_if: Management0
    provider_kind: ceos
    image:
      clab: ceos:4.25.1F
    group_vars:
      ansible_user: admin
      ansible_ssh_pass: admin
      ansible_become: yes
      ansible_become_method: enable
```

One of the first steps in the transformation process would then be to choose the correct device settings based on the provider, effectively merging **device._type_._provider** into **device._type_** and then removing all entries that correspond to keys in **provider** dictionary, resulting in clean provider-specific device defaults.

So far, this hasn't solved @jbemmel challenge a bit, we still have to figure out how to identify provider-specific settings. We could implement one of these options:

### Provider data identified by provider name

Imagine the following device settings (edited for brevity):

```
eos:
  interface_name: Ethernet%d
  mgmt_if: Management1
  image:
    libvirt: arista/veos
    virtualbox: arista/veos
  clab:
    provider_interface_name: eth%d
    mgmt_if: Management0
    clab:
      kind: ceos
    image:
      clab: ceos:4.25.1F
```

After merging **devices.eos.clab** with **devices.eos**, we'd still have **clab** key in **devices.eos** (yeah, I know, I have to be careful in the merge-and-cleanup process), and then we just need to add a rule saying "copy **devices._type_._provider** straight into node data".

### Provider attributes listed in **provider** settings

Assuming the **clab.attributes** settings @jbemmel proposed, we'd have the following device settings:

```
eos:
  interface_name: Ethernet%d
  mgmt_if: Management1
  image:
    libvirt: arista/veos
    virtualbox: arista/veos
  clab:
    provider_interface_name: eth%d
    mgmt_if: Management0
    kind: ceos
    image:
      clab: ceos:4.25.1F
```

After the merge, **kind** would become a key under **eos**, but then we'd go through provider-specific attributes and move **eos.kind** into **eos.clab.kind**, and copy **eos.clab** into node data (same as the other solution).

Which one do you like more?

**Comment by jbemmel** [comment]
I would prefer to have provider specific attributes in a sub-context under each node, easily identifiable

Assuming we maintain the global/node/link hierarchy, one could have something like this:
```
host_vars.yml

hostname: srl1
ansible_network_os: srlinux
clab:
 kind: ixrd2 # node-level
interfaces:
- name: to-srl2
  clab:
   interface_name: eth1 # link-level
```
