### ISSUE TITLE
VLAN implementation / feature design

### ISSUE THREAD

**Issue by ssasso** [ipspace/netsim-tools#143]
Starting the feature design discussion with my proposal.

Some devices used on netsim may need to support VLANS / switchports on links ("L3 switch behaviour").
Some others may only need to support sub-interface tagging ("router behaviour").

Generically speaking, a "switch node" may have the following attributes:
```
nodes:
  switch_node:
    vlans:
    - id: 5
      prefix: 1.2.3.0/24
```
(the **prefix** key will trigger an IP assignment to the SVI)

At the same time, the **link** needs to have some additional attributes:
```
links:
- switch_node:
    switchport:
      mode: access
      native_vlan: 5
  host_node:
- switch_node:
    switchport:
      mode: trunk
      vlans: [ 5 ]
      native_vlan: 1
  router_node:
    dot1q:
      vlan: 5
```

**Comment by ssasso** [comment]
The example before is for "p2p" links, which may be not so useful i.e. for trunks.
But this will be a more real situation with "lan" links (NOTE: vlan filtering on linux bridges is required):
```
links:
- switch_node:
    switchport:
      mode: trunk
      vlans: [ 10, 20, 30]
  host_node_a:
    vlan: 10
  host_node_b:
    vlan: 20
  host_node_c:
    vlan: 30
```

**Comment by jbemmel** [comment]
I think we would need a global list of vlan definitions, instead of per node. For example:
```
links:
- switch_node1:
    switchport:
      mode: trunk
      vlans: [10, 20, 30]
  switch_node2:
    switchport:
      mode: trunk
      vlans: [10, 20, 30]
  host_node_a:
    vlan: 10
  host_node_b:
    vlan: 20
  host_node_c:
    vlan: 30
```
It is hard to define what 'vlan:30' in host_node_c refers to in this case, if not a global list

The list should be indexed by name, not VLAN tag, as one could have multiple different VLANs 10 (on different nodes).

**Comment by ssasso** [comment]
The reason why I put the vlan definition inside a node is because a VLAN may have a different scope in different nodes.
(i.e., thinking big, VLAN 10 can be part of VNI 50010 on node "a", while it can be VNI 60010 on node "b").

However you are right, it may be hard do use a vlan id in a link if there's no global definition.

Maybe we can keep it simple and avoid VLAN ID "reusing" for multiple scopes.

**Comment by ipspace** [comment]
We have two problems to solve (as always): naming and addressing ;)

Also, we shouldn't look at the VLAN module in isolation -- it needs to result in addressing and interfaces. Furthermore, some people might want to use VLANs with local significance (per port), others need segments with global significance (L2 services, VXLAN/EVPN).

Next challenge: a VLAN endpoint could be a L2-only endpoint, or an SVI interface (a router attached to an internal bridge), or a subinterface (routed interface attached to a VLAN).

With that in mind, it probably makes sense to start with #103 and add VLAN ID to subnet attributes. That would give us:

* Names instead of IDs
* Global VLANs
* Global subnet-level addressing

We could also allow locally-significant VLANs -- use numbers instead of names.

Next, have to decide who will do VLAN tagging: Linux bridge or attached devices. The answer is obvious for trunk interfaces, but what about access interfaces? Should we expect the network device to use native VLAN on access ports or should we configure Linux bridge to do access port tagging?

Now for the data model. I would try to keep it simple, for example:

```
links:
- switch_node1:
    vlan:
      trunk: [ A, B, C ]   # defined in subnets
  switch_node2:
    vlan:
      trunk: [ A, B, C, 40 ]
  host_node_a:
    vlan:
      access: A
  host_node_b:
    vlan: A            # implies "access: A"
  host_node_c:
    vlan: 40
```
 
We could also add **type** attribute (**routed** or **vlan**), with **routed** being assumed for access ports and **vlan** for trunk ports. A L2 switch (VLAN interfaces) and an edge router (subinterfaces) connected to the same VLAN would be described this way:

```
links:
- switch:
    vlan:
      trunk: [ A, B, C ]   # defined in subnets
  router:
    vlan:
      trunk: [ A, B, C ]
      type: routed
```
 
Then there's the obvious question of addressing. Effectively we need the whole addressing shtick (fixed addresses, node ID, l2only...) for every VLAN segment.

Welcome to L2 hell 🥴🤷‍♂️

**Comment by jbemmel** [comment]
```
links:
- switch:
    vlan: [ A, B, C ]  # defined in subnets
  router:
    vlan:
     A:
     B:
     C:
     type: routed
```
?
