### ISSUE TITLE
Set image default version for nodes in topology file

### ISSUE THREAD

**Issue by JulioPDX** [ipspace/netsim-tools#202]
Reading the docs it looks like this is possible when using libvirt. From the docs below.

```yaml
---
defaults:
  device: eos
  devices:
    eos:
      image:
        libvirt: arista/vEOS-lab-4.21.14M
```

As a simple user, I assumed the same would be possible when using Containerlab as the provider. Please see my example below.

```yaml
---
defaults:
  device: eos
  devices:
    eos:
      image:
        clab: coes:4.27.2F
```

When running `netlab create`, this will create all files but image referenced in the `clab.yml` file is the default setting and not one specified by user.  Example below.

```yaml
topology:
  nodes:
    R1:
      kind: ceos
      image: ceos:4.25.1F
```

I think this would be a great addition and provide users with a similar experience, no matter what the provider is. Thank you for creating netsim-tools, pretty sweet so far.

**Comment by jbemmel** [comment]
Try
```
defaults:
 device: srlinux
 devices:
  srlinux.clab.image: ghcr.io/nokia/srlinux:latest
  eos.clab.image: ceos:latest
```

**Comment by jbemmel** [comment]
I agree there are some inconsistencies that should be fixed though

**Comment by jbemmel** [comment]
For example, in topology-defaults.yml:
```
  cumulus:
    interface_name: swp%d
    mgmt_if: eth0
    image:
      libvirt: CumulusCommunity/cumulus-vx:4.4.0
      virtualbox: CumulusCommunity/cumulus-vx:4.3.0
    group_vars:
      ansible_user: vagrant
      ansible_ssh_pass: vagrant
      ansible_network_os: cumulus
      ansible_connection: paramiko
    features:
      initial:
        ipv4:
          unnumbered: True
        ipv6:
          lla: True
      ospf:
        unnumbered: True
    clab:
      mtu: 1500
      runtime: docker
      node:
        kind: cvx
      image: networkop/cx:4.3.0
      group_vars:
        ansible_connection: docker
        ansible_user: root
```
