### ISSUE TITLE
Group node_data cannot be used to set node device type

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#223]
Wanted to set device type for groups of devices with `node_data`. Looks like the device check happens before the group variables are copied into nodes, so it failed.

Example:

```
groups:
  iosv:
    node_data:
      device: iosv
    members: [ pe1, p1, rr, ce2 ]
  eos:
    node_data:
      device: eos
    members: [ pe2, p2, ce1 ]

nodes: [ pe1, pe2, p1, p2, rr, ce1, ce2 ]
```
