### ISSUE TITLE
Better error messages on incorrect top-level topology elements

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#237]
From @barajus:

---
Example:
```
vrfs:
  red:
  blue:

nodes:
  spine01:
    module: [ bgp]
````

results in ...

```
IncorrectValue in topology: Unknown top-level element vrfs
```
---

A better error message would say "you need to add VRF module"
