### ISSUE TITLE
IP Address assignment broken with VLAN Trunk

### ISSUE THREAD

**Issue by ssasso** [ipspace/netsim-tools#270]
While trying to implement VLAN Trunk support in VyOS, I encountered some issues in the IP Address assignment, when using *access* and *trunk* mode in different links.

Topology:
```
---
vlans:
  red:
    mode: irb
  blue:
    mode: irb

nodes:
  h1:
    device: vyos
    module: []
  s1:
    device: eos
    module: [ vlan ]
  s2:
    device: vyos
    module: [ vlan ]
  h2:
    device: vyos
    module: []

links:
- s1:
  s2:
  vlan.trunk: [ red, blue ]
- s2:
    vlan.access: red
  h2:
- s1:
    vlan.access: blue
  h1:
```

This seems to result in 4 different lan pools used. See the following extract from *s2* host_vars:
```
vlans:
  blue:
    bridge_group: 2
    id: 1001
    mode: irb
    neighbors:
    - ifname: eth1
      ipv4: 172.16.1.1/24
      node: h1
    - ifname: Vlan1001
      ipv4: 172.16.1.2/24
      node: s1
    - ifname: br0.1001
      ipv4: 172.16.2.3/24
      node: s2
    prefix:
      ipv4: 172.16.1.0/24
    vni: 101001
  red:
    bridge_group: 1
    id: 1000
    mode: irb
    neighbors:
    - ifname: br0.1000
      ipv4: 172.16.0.3/24
      node: s2
    - ifname: Vlan1000
      ipv4: 172.16.3.2/24
      node: s1
    - ifname: eth1
      ipv4: 172.16.0.4/24
      node: h2
    prefix:
      ipv4: 172.16.0.0/24
    vni: 101000
```
