### ISSUE TITLE
Broken iBGP for VRF

### ISSUE THREAD

**Issue by ssasso** [ipspace/netsim-tools#279]
While working on #278 I found an issue on iBGP with VRF.

It seems that, when using iBGP with VRF, the bgp peers are not reported on the specific vrf dict, but they are on the "main" bgp dict.

Example with eBGP:
```
defaults.device: eos

vrfs:
  red:

module: [ bgp, vrf ]

nodes:
  r1:
    bgp.as: 65001
  r2:
    bgp.as: 65002

links:
- r1: { vrf: red }
  r2: { vrf: red }
```

Working *host_vars/r1* (subset):
```
vrfs:
  red:
    af:
      ipv4: true
    bgp:
      neighbors:
      - as: 65002
        ifindex: 1
        ipv4: 10.1.0.2
        name: r2
        type: ebgp
```

But, when using iBGP (i.e., with OSPF):
```
defaults.device: eos

vrfs:
  red:

module: [ ospf, bgp, vrf ]
bgp.as: 65000

nodes:
  r1:
  r2:

links:
- r1: { vrf: red }
  r2: { vrf: red }
```

the peers are reported on the main bgp dict:
```
# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
  vpnv4: true
bgp:
  advertise_loopback: true
  as: 65000
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - as: 65000
    ipv4: 10.0.0.2
    name: r2
    type: ibgp
  next_hop_self: true
  router_id: 10.0.0.1
box: arista/veos
[...]
vrf:
  as: 65000
vrfs:
  red:
    af:
      ipv4: true
    export:
    - '65000:1'
    import:
    - '65000:1'
    ospf:
      active: true
      area: 0.0.0.0
      interfaces:
      - ifindex: 1
        ifname: Ethernet1
        ipv4: 10.1.0.1/30
        linkindex: 1
        name: r1 -> r2
        neighbors:
        - ifname: Ethernet1
          ipv4: 10.1.0.2/30
          node: r2
        ospf:
          area: 0.0.0.0
          network_type: point-to-point
          passive: false
        type: p2p
        vrf: red
      router_id: 10.0.0.1
    rd: '65000:1'
    vrfidx: 100
```
