### ISSUE TITLE
VLAN access interface removes clab:name attribute from physical interface

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#283]
Haven't been following developments recently, but as I was trying to add VLAN support for SR Linux I hit an issue with the custom provider attributes.

Basically, for example in the vlan-access-node.yml input test:
```
interfaces:

- bridge: input_2

  ifindex: 1

  ifname: ethernet-1/1

  linkindex: 2

  type: lan

  vlan:

    access: blue

    access_id: 1001

- bridge: input_3

  ifindex: 2

  ifname: ethernet-1/2

  linkindex: 3

  type: lan

  vlan:

    access: blue

    access_id: 1001

- bridge_group: 1

  clab:

    name: e1-1

  ifindex: 3

  ifname: vlan1001

  ipv4: 172.16.1.3/24

  name: VLAN blue (1001) -> [s1,h2]

  neighbors:

  - ifname: ethernet-1/2

    ipv4: 172.16.1.2/24

    node: s1

  - ifname: eth1

    ipv4: 172.16.1.4/24

    node: h2

  type: svi

  virtual_interface: true

  vlan_name: blue
```

note how clab name e1-1 is generated for the virtual interface vlan1001, while it is only used & needed for both physical (non-virtual) links
