### ISSUE TITLE
vlan id for 'blue' vlan not available to s1

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#285]
Generated from https://github.com/ipspace/netsim-tools/blob/dev/tests/topology/input/vlan-access-node.yml
(modified to use SR Linux nodes)

The data for s1 don't include the blue vlan id 1001, perhaps the example should not have this line? https://github.com/ipspace/netsim-tools/blob/dev/tests/topology/input/vlan-access-node.yml#L23
```
vlans:

  blue:

    host_count: 0

    neighbors: {}

  red:

    bridge_group: 1

    host_count: 1

    id: 1000

    neighbors:

    - ifname: eth1

      ipv4: 172.16.0.1/24

      node: h1

    - ifname: ethernet-1/1.1000

      ipv4: 172.16.0.2/24

      node: s1

    prefix:

      ipv4: 172.16.0.0/24

    vni: 101000

```
