### ISSUE TITLE
Routed VLAN subinterfaces on Vyos and OS10

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#289]
0defd8e963a53ca6889d23e164f490199e974b41 added support for routed VLAN subinterfaces. @ssasso: It would be great to have them on VyOS and OS10 (they are already implemented on IOSv and EOS).

Any feedback on VLAN developer documentation https://netsim-tools.readthedocs.io/en/dev/dev/config/vlan.html would also be highly appreciated.

**Comment by ssasso** [comment]
Working on the VyOS stuff, but I am on a blocking point:
When you work on formatting the `vlan_subif_name`, you are using `**parent_intf`, adding the attribute `subif_index`:
https://github.com/ipspace/netsim-tools/blob/0defd8e963a53ca6889d23e164f490199e974b41/netsim/modules/vlan.py#L687

However, this does not have the VLAN ID in it (or, at least, it's not easily accessible), which unfortunately is required for setting the right interface name in VyOS (subintf must match the vlan tag).

Quick and dirty workaround I'm using right now is:
```
    if 'trunk_id' in parent_intf.vlan:
      parent_intf.vlan_id = parent_intf.vlan.trunk_id[0]
```
which allows me to use:
```
vlan_subif_name: "{ifname}.{vlan_id}"
```

**Comment by ssasso** [comment]
Additionally:

most probabily I am doing it in the wrong way on the topology file (maybe a full example like that could be useful on the documentation?):
```
---
module: [ vlan, vrf ]

vlans:
  red:
    vrf: red
  blue:
    vrf: blue
  green:
    vrf: green

vrfs:
  red:
  blue:
  green:

nodes:
  r1:
    device: vyos
    vlans:
      red:
        mode: route
      blue:
        mode: route
      green:
        mode: route
  s1:
    device: vyos
    vlans:
      red:
        mode: irb
      blue:
        mode: irb
      green:
        mode: irb

links:
- s1:
    vlan.trunk: [ red, blue, green ]
  r1:
    vlan.trunk: [ red, blue, green ]
```

BUT VRF data is not reported on the *r1* node (nor at the global node level, or at the interface level).
