### ISSUE TITLE
VLAN data must be copied into routed interface data

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#292]
Most probabily I am doing it in the wrong way on the topology file (maybe a full example like that could be useful on the documentation?):
```
---
module: [ vlan, vrf ]

vlans:
  red:
    vrf: red
  blue:
    vrf: blue
  green:
    vrf: green

vrfs:
  red:
  blue:
  green:

nodes:
  r1:
    device: vyos
    vlans:
      red:
        mode: route
      blue:
        mode: route
      green:
        mode: route
  s1:
    device: vyos
    vlans:
      red:
        mode: irb
      blue:
        mode: irb
      green:
        mode: irb

links:
- s1:
    vlan.trunk: [ red, blue, green ]
  r1:
    vlan.trunk: [ red, blue, green ]
```

BUT VRF data is not reported on the *r1* node (nor at the global node level, or at the interface level).

_Originally posted by @ssasso in https://github.com/ipspace/netsim-tools/issues/289#issuecomment-1146617940_
