### ISSUE TITLE
Node-level 'vlan.mode' is not taken in account on VLAN trunks

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#295]
Sample topology:

```
vlans:
  red:
  blue:
  green:
    mode: route

nodes:
  r1:
    device: eos
    vlan.mode: route
  s1:
    device: eos
    vlan.mode: bridge

links:
- s1:
  r1:
  vlan.trunk: [ red, green, blue ]
```
