### ISSUE TITLE
Trunk interface VLAN mode is set to 'route' if one VLAN has 'mode: route'

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#297]
Sample topology:

```
module: [ vlan ]

vlans:
  red:
  blue:
  green:
    vrf: green
    mode: route

nodes:
  r2:
    device: eos
    vlans:
      red:
        mode: route
      blue:
        mode: route
  s2:
    device: iosv

links:
- s2:
  r2:
  vlan.trunk: [ red, green, blue ]
```

Unexpected result on nodes.s2.interfaces:

```
- ifindex: 1
  ifname: GigabitEthernet0/1
  linkindex: 1
  name: s2 -> r2
  neighbors:
  - ifname: Ethernet1
    node: r2
  subif_index: 3
  type: p2p
  vlan:
    mode: route
```
