### ISSUE TITLE
Incorrect routed subinterface name in per-VLAN list of neighbors

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#300]
Sample topology:

```
module: [ vlan ]

vlans:
  red:
  blue:
  green:

nodes:
  r2:
    device: iosv
  s2:
    device: iosv

links:
- s2:
  r2:
    vlan.trunk:
      red:
        vlan.mode: route
  vlan.trunk: [ red, green, blue ]
```

Incorrect interface name in **red** VLAN neighbors:

```
red:
  host_count: 0
  id: 1000
  neighbors:
  - ifname: GigabitEthernet0/4
    ipv4: 172.16.0.1/24
    node: r2
  - ifname: BVI3
    ipv4: 172.16.0.2/24
    node: s2
  prefix:
    ipv4: 172.16.0.0/24
  vni: 101000
```

`GigabitEthernet0/4` should have been `GigabitEthernet0/1.3` (or similar)
