### ISSUE TITLE
VLAN `mode` attribute should be copied into `vlan.mode` link or interface attribute

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#301]
Sample topology:

```
module: [ vlan ]

vlans:
  red:
    mode: bridge
  blue:
  green:

nodes:
  r2:
    device: iosv
  s2:
    device: iosv

links:
- s2:
    vlan.trunk:
      green:
        vlan.mode: bridge
  r2:
    vlan.trunk:
      red:
        vlan.mode: route
  vlan.trunk: [ red, green, blue ]
```

Interface attribute for red BVI interface on S2 should be `vlan.mode` and not `mode`:

```
- bridge_group: 3
  ifindex: 7
  ifname: BVI3
  mode: bridge
  name: VLAN red (1000) -> [r2]
  neighbors:
  - ifname: GigabitEthernet0/4
    ipv4: 172.16.0.1/24
    node: r2
  type: svi
  virtual_interface: true
  vlan_name: red
```
