### ISSUE TITLE
Global VLAN attributes are not propagated to nodes attached to VLAN access links

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#302]
Global VLAN attributes should apply to all links using those VLANs, but they are applied to VLAN interfaces not links, so they are not propagated to non-VLAN nodes.

Sample topology:
```
vlans:
  red:
    ospf.cost: 10

nodes:
  r2:
    module: [ ospf ]
    device: eos
  s2:
    module: [ vlan, ospf ]
    device: iosv

links:
- s2:
    vlan.access: red
  r2:
```

OSPF cost is not applied to R2 interface:

```
- bridge: X_1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 172.16.0.1/24
  linkindex: 1
  name: r2 -> [s2]
  neighbors:
  - ifname: BVI1
    ipv4: 172.16.0.2/24
    node: s2
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: lan
  vlan_name: red
```
