### ISSUE TITLE
Module attributes propagated to interfaces on nodes without that module

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#303]
Sample topology:

```
vrfs:
  red:

nodes:
  r1:
    module: [ vrf ]
    device: eos
  h1:
    device: linux

links:
- r1:
  h1:
  vrf: red
```

Interface on H1 should not have VRF attributes as H1 does not use VRF module. What we get instead:

```
af:
  ipv4: true
box: generic/ubuntu2004
device: linux
id: 2
interfaces:
- bridge: X_1
  gateway:
    ipv4: 172.16.0.1/24
  ifindex: 1
  ifname: eth1
  ipv4: 172.16.0.2/24
  linkindex: 1
  name: h1 -> [r1]
  neighbors:
  - ifname: Ethernet1
    ipv4: 172.16.0.1/24
    node: r1
  role: stub
  type: lan
  vrf: red
mgmt:
  ifname: eth0
  ipv4: 192.168.121.102
  mac: 08-4F-A9-00-00-02
name: h1
role: host
```
