### ISSUE TITLE
Wrong VLAN module attribute set when using native VLAN

### ISSUE THREAD

**Issue by ssasso** [ipspace/netsim-tools#306]
Given this *topology-defaults*:
```
  routeros:
    features:
      vlan:
        svi_interface_name: bridge{vlan}
        vlan_subif_name: "{ifname}-{vlan.access_id}"
```
And trying to use a *native vlan* on the topology:
```
nodes:
  r1:
    device: routeros
    vlans:
      red:
        mode: route
      blue:
        mode: route
      green:
        mode: route
  s1:
    device: routeros
    vlans:
      red:
        mode: irb
      blue:
        mode: irb
      green:
        mode: irb
  h1:
    device: linux

links:
- s1:
    vlan.trunk: [ red, blue, green ]
    vlan.native: green
  r1:
    vlan.trunk: [ red, blue, green ]
    vlan.native: green
- s1:
    vlan.access: red
  h1:
```

The following *host_vars* topology file is produced (reporting only the relevant part):
```
- ifindex: 4
  ifname: ether2-1002
  parent_ifindex: 2
  parent_ifname: ether2
  type: vlan_member
  virtual_interface: true
  vlan:
    access: blue
    access_id: 1001
- ifindex: 5
  ifname: ether2-1002
  parent_ifindex: 2
  parent_ifname: ether2
  type: vlan_member
  virtual_interface: true
  vlan:
    access: red
    access_id: 1000
```

I was expecting that the ID used on the *ifname* should use the same ID as reported on *access_id*.

(Without the native VLAN everything is good)
