### ISSUE TITLE
Testing connect.sh requires Ansible

### ISSUE THREAD

**Issue by bbros-dev** [ipspace/netsim-tools#31]
According to this Github workflow error we require Ansible to test `connect.sh`:

https://github.com/bbros-dev/netsim-tools/runs/2711305963?check_suite_focus=true#step:7:137

We're Salt users so have no idea about Ansible and whether this can be resolved some other way.
We'll pull Ansible into the workflow and settle for that workaround - it feels wrong to require Ansible to establishing a SSH or docker exec connection.

Suspect there is a better solution, but we need to move on.

**Comment by bbros-dev** [comment]
@ipspace any thoughts on how to remove `ansible-inventory` from the `connect.sh`?

It's wercking havoc with the CICD tests and it [now appears to have been installed](https://github.com/bbros-dev/netsim-tools/runs/2711617326?check_suite_focus=true#step:4:80):

https://github.com/bbros-dev/netsim-tools/runs/2711617326?check_suite_focus=true#step:7:137

**Comment by bbros-dev** [comment]
We believe we've found the way to remove the `connect.sh` dependency on `ansible-inventory` at least for the containerlab provider.  

Incremental steps.

For this specific use case two pieces of information are provided to `connect.sh`by `ansible-inventory`:

1. `ansible_connection`
2. `ansible_host`

The required data is generated by the `--expanded` option.
If we make this data available by default we can eliminate the `connect.sh` dependency on `ansible-inventory` - for the docker use cases.

So the question is where should this data be extracted to?

There are two possibilities - as we see it:

1. Existing: `hosts.yml`
2. New: `connect.yml`

Eventually it is natural to want to mix providers (VM+container) so perhaps the natural place is `hosts.yml`, which would **by default** look like:

```
frr:
  hosts:
    c1:
      ansible_connection: docker
      ansible_host: clab-base-c1
      id: 3
    c2:
      ansible_connection: docker
      ansible_host: clab-base-c2
      id: 4
    e1:
      ansible_connection: docker
      ansible_host: clab-base-e1
      id: 2
    e2:
      ansible_connection: docker
      ansible_host: clab-base-e2
      id: 5
```

Thoughts?
