### ISSUE TITLE
ospf.network_type attribute not set for interfaces of type 'lan'

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#322]
In the multi-vrf example at https://github.com/ipspace/netsim-examples/blob/master/VRF/vrf-lite-routers/multi-vrf.yml CE-router cr1 is connected to a lan network with pe1 and pe2

The resulting topology file looks like this:
```
interfaces:
- bridge: vrf-lite-r_1
  clab:
    name: e1-1
  ifindex: 1
  ifname: ethernet-1/1
  ipv4: 172.16.0.3/24
  linkindex: 1
  name: cr1 -> [pe1,pe2]
  neighbors:
  - ifname: ethernet-1/1
    ipv4: 172.16.0.1/24
    node: pe1
  - ifname: ethernet-1/1
    ipv4: 172.16.0.2/24
    node: pe2
  ospf:
    area: 0.0.0.0
    cost: 10
    passive: false
  type: lan
```

Note how there is no 'network_type' attribute for ospf, breaking all platforms
